apiVersion: v1
kind: Pod
metadata:
  labels:
    app: questions-store
  name: questions-store
spec:
  containers:
  - image: chaimamnsr/questions-store:latest
    name: questions-store
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 3
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 3
    envFrom:
    - configMapRef:
        name: questions-store-config
    - secretRef:
        name: questions-store-secret