apiVersion: v1
kind: Service
metadata:
  name: questions-store-service
  labels:
    app: questions-store
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: questions-store
